### ISSUE TITLE
Is there or will there be support for fine-tuning based on the property prediction task (i.e., weight transfer functionality) ? 

### ISSUE THREAD

**Issue by asboppana** [DeepGraphLearning/torchdrug#11]

**Comment by KiddoZhu** [comment]
Hi! I think this is already easy to implement in TorchDrug.

Because models and tasks are separated in TorchDrug, you can define a representation learning model, wrap it in a pretraining task and a finetuning task. You first train the pretraining task and then train the finetuning task.

I just checked the tutorial of pretrained molecular representation, and it misses tge steps of finetuning. We will update it later.

**Comment by KiddoZhu** [comment]
Finetuning is now in the tutorial of pretrained molecular representations. Please refer to that if you need it.
