### ISSUE TITLE
example 中的例子不能完美运行

### ISSUE THREAD

**Issue by CuiDachao** [DeepGraphLearning/torchdrug#41]
项目开始介绍页使用的 td.CARBON 没有引用来源，无法展示项目功能

**Comment by CuiDachao** [comment]
需要增加`import torchdrug as td`在文件开始

**Comment by KiddoZhu** [comment]
Hi! Thanks for pointing out the bug. As GitHub is a global and inclusive place, we would advocate using English instead of other languages.

For non-Chinese users
------------------------

This issue is about the missing reference of `td.CARBON` in the quick start. This can be solved by adding a line `import torchdrug as td` at the beginning.
