### ISSUE TITLE
Some questions about KnowledgeBaseGraphAttentionNetwork model

### ISSUE THREAD

**Issue by fridayL** [DeepGraphLearning/torchdrug#54]
Hi: I have some questions about KnowledgeBaseGraphAttentionNetwork model,  the code at kbgat.py , the kbgat inherit  GAT method.  But in the original paper, there is also  attention code for different relations, but at  kbgat.py can not find attention for multi-type relations,  maybe I miss something for this code,  or kbgat.py did not fully code refer to the original paper? thanks

**Comment by mnqu** [comment]
Thanks for the question!

As Zhaocheng mentioned, KBGAT uses a different evaluation protocol. This protocol can be problematic in cases where entities have tied scores as pointed out in the ACL paper shared by Zhaocheng. Because of that, we change the evaluation protocol in our KBGAT implementation to the protocol used in other knowledge graph reasoning models.

With this change of evaluation protocol, we found that the result of our GAT implementation is comparable to the result of the GAT implementation in KBGAT, although there are some minor differences as you mentioned (e.g., attention for multi-type relations). Therefore, we use our GAT implementation for KBGAT, in order to make the package more consistent.
