### ISSUE TITLE
Atom vocabulary and Atom valence map hardcoded and is limited

### ISSUE THREAD

**Issue by Jblauvs** [DeepGraphLearning/torchdrug#73]
Hey, 
Attempting to use torchdrug for a generation task and have a large dataset of smiles for pretraining.  
Am running into issues where atoms don't exist in the vocabulary and also during generation the valence check fails because the proper atomic number is not in the valence map.  

```
ValueError: Fail to check valence. Unknown atom type 11
```

Am I missing a step?  There isn't a lot of documentation I can find about using custom data, only preloaded datasets. 

The hard coded mappings are here:

Valence:
https://github.com/DeepGraphLearning/torchdrug/blob/a93356e883e5b971a8b9b6d0f5cb7f19d60ff7ba/torchdrug/data/molecule.py#L37

Atoms:
https://github.com/DeepGraphLearning/torchdrug/blob/master/torchdrug/data/feature.py#L9

Should I just add my new atoms to the source code?
Thanks, 
James

**Comment by shichence** [comment]
* Hi, Torchdrug is mainly designed for organic molecules and some metals are not included in the vocab (e.g. sodium (Na) in your case).
* The raised error is due to the function `is_valid`, which is a coarse implementation of valence check that can be accelerated by GPU. You can always replace the function with `is_valid_rdkit`, a slower but more accurate validity check function with API from RDKit.
* Yes, you can add your new atoms in the source code. Otherwise, it will be parsed as a unknown atom type https://github.com/DeepGraphLearning/torchdrug/blob/a93356e883e5b971a8b9b6d0f5cb7f19d60ff7ba/torchdrug/data/feature.py#L34

**Comment by Jblauvs** [comment]
Great, thanks for the response.  
Just making sure I was using the repo correctly, it sounds like it can be extended to my use case easily.  
Cheers, 
James
